// AUTO-GENERATED by scripts/generate-products.ts from content/products/*.json
// DO NOT EDIT THIS FILE MANUALLY - edit the JSON files in content/products/ instead.

export type Product = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    price: number;
    originalPrice?: number;
    image: string;
    images?: string[];
    badge?: string;
    category: string;
    productLine: 'footwear' | 'organics' | 'clothing';
    weight?: string;
    sizes?: { label: string; price: number }[];
    variants?: { size: string; price: number }[];
    colors?: string[];
    ingredients?: string[];
    howToUse?: string[];
    careInstructions?: string[];
    benefits?: string[];
    sizeOptions?: { label: string; price: number }[];
    skinHairType?: string;
    usage?: string;
    scale?: number;
    rotate?: number;
};

export const products: Product[] = [
    {
      id: "o3",
      name: "Rosemary Hair Toner",
      shortDescription: "Herbal Hair Spray Toner for long hair.",
      description: "Herbal Haven by Nashra Rosemary Hair Toner. Promotes long hair and helps to stop hairfall. Perfect for daily use to keep your hair healthy and strong.",
      price: 800,
      category: "hair-care",
      productLine: "organics",
      image: "/images/rosemary-hair-toner.png",
      images: ["/images/rosemary-hair-toner.png"],
      variants: [
        {
          size: "200ml",
          price: 800
        }
      ],
      benefits: ["Promotes long hair", "Stops hairfall"],
      howToUse: ["Spray directly onto scalp and hair roots"]
    },
    {
      id: "o4",
      name: "Teeth Whitening Powder",
      shortDescription: "Herbal powder for white and strong teeth.",
      description: "Herbal Haven by Nashra Teeth Whitening Powder. Made with natural herbs to keep your teeth white, strong, and healthy. It also helps relieve pain and removes swelling.",
      price: 600,
      category: "skin-care",
      productLine: "organics",
      image: "/images/teeth-whitening-powder.png",
      images: ["/images/teeth-whitening-powder.png"],
      variants: [
        {
          size: "100g",
          price: 600
        },
        {
          size: "300g",
          price: 1800
        }
      ],
      benefits: ["Teeth whitening", "Strong teeth", "Relieves pain", "Removes swelling"],
      howToUse: ["Apply a small amount to your toothbrush and brush gently"]
    },
    {
      id: "o5",
      name: "Whitening Herbal Ubtan",
      shortDescription: "Herbal mud mask powder for bright, clear skin.",
      description: "Herbal Haven by Nashra Whitening Herbal Ubtan (Mud Mask). This natural blend makes the skin tight and bright, removes roughness, and clears acne for a flawless complexion.",
      price: 600,
      category: "skin-care",
      productLine: "organics",
      image: "/images/ubtan-powder.png",
      images: ["/images/ubtan-powder.png"],
      variants: [
        {
          size: "100g",
          price: 600
        }
      ],
      benefits: ["Skin tight and bright", "Removes roughness", "Clears acne"],
      howToUse: ["Mix with water or rose water to form a paste. Apply to skin and let it dry before washing."]
    },
    {
      id: "o6",
      name: "Whitening Cream",
      shortDescription: "Herbal Haven Whitening Cream for glowing skin.",
      description: "Herbal Haven by Nashra Whitening Cream. Nourishes the skin and promotes a bright, glowing complexion using natural herbal extracts.",
      price: 800,
      category: "skin-care",
      productLine: "organics",
      image: "/images/whitening-cream.png",
      images: ["/images/whitening-cream.png"],
      variants: [
        {
          size: "35g",
          price: 800
        },
        {
          size: "50g",
          price: 1200
        }
      ],
      benefits: ["Brightens skin", "Promotes glowing complexion"],
      howToUse: ["Apply gently to the face and neck before sleeping."]
    },
    {
      id: "o7",
      name: "Body Scrub (Viscous Flavour)",
      shortDescription: "Herbal body scrub for soft skin.",
      description: "Herbal Haven by Nashra Body Scrub. Leaves skin feeling incredibly soft and helps remove wrinkles. (Note: Cannot be used on the face).",
      price: 800,
      category: "skin-care",
      productLine: "organics",
      image: "/images/placeholder.png",
      images: ["/images/placeholder.png"],
      variants: [
        {
          size: "300g",
          price: 800
        }
      ],
      benefits: ["Soft skin", "Removes wrinkles"],
      howToUse: ["Apply to body during bath. Do not use on face."]
    },
    {
      id: "o8",
      name: "Whitening Serum",
      shortDescription: "Herbal Haven Whitening Serum.",
      description: "Herbal Haven by Nashra Whitening Serum. Promotes a bright, glowing complexion.",
      price: 900,
      category: "skin-care",
      productLine: "organics",
      image: "/images/placeholder.png",
      images: ["/images/placeholder.png"],
      variants: [
        {
          size: "50g",
          price: 900
        }
      ],
      benefits: ["Skin whitening"],
      howToUse: ["Apply gently to the face."]
    },
    {
      id: "o9",
      name: "Herbal Haven By Nashrah Skin Polish",
      shortDescription: "Herbal Haven Skin Polish with whitening agents.",
      description: "Herbal Haven by Nashra Skin Polish. Ready to use formula with powerful whitening agents for an instant glow.",
      price: 900,
      category: "skin-care",
      productLine: "organics",
      image: "/images/skin-polish.png",
      images: ["/images/skin-polish.png"],
      variants: [
        {
          size: "300g",
          price: 900
        }
      ],
      benefits: ["Ready to use", "Contains whitening agents"],
      howToUse: ["Apply evenly to the skin and follow standard polishing procedures."]
    },
    {
      id: "o10",
      name: "Rosemary, Amla & Reetha Shampoo",
      shortDescription: "Herbal shampoo for strong hair.",
      description: "Herbal Haven Shampoo with Rosemary, Amla, and Reetha. Formulated to strengthen hair from the roots.",
      price: 1000,
      category: "hair-care",
      productLine: "organics",
      image: "/images/keratin-shampoo.png",
      images: ["/images/keratin-shampoo.png"],
      variants: [
        {
          size: "200g",
          price: 1000
        }
      ],
      benefits: ["Strong hair"],
      howToUse: ["Apply to wet hair, massage into a lather, and rinse."]
    },
    {
      id: "o11",
      name: "Hibiscus Hair Growth Shampoo",
      shortDescription: "Herbal Viscous Shampoo.",
      description: "Herbal Haven Viscous Shampoo. Thick, rich formula for cleansing and nourishing the hair.",
      price: 1200,
      category: "hair-care",
      productLine: "organics",
      image: "/images/hibiscus-shampoo.png",
      images: ["/images/hibiscus-shampoo.png"],
      variants: [
        {
          size: "200g",
          price: 1200
        }
      ],
      benefits: ["Deep cleansing"],
      howToUse: ["Apply to wet hair, massage well, and rinse."]
    },
    {
      id: "o12",
      name: "Rice & Flexseeds Shampoo",
      shortDescription: "Nourishing shampoo with rice and flaxseeds.",
      description: "Herbal Haven Rice & Flexseeds Shampoo. A deeply nourishing blend to improve hair texture and promote healthy growth.",
      price: 1200,
      category: "hair-care",
      productLine: "organics",
      image: "/images/placeholder.png",
      images: ["/images/placeholder.png"],
      variants: [
        {
          size: "200g",
          price: 1200
        }
      ],
      benefits: ["Improves hair texture", "Nourishing"],
      howToUse: ["Apply to wet hair, lather gently, and rinse thoroughly."]
    },
    {
      id: "o13",
      name: "Hair Growth Oil",
      shortDescription: "Herbal oil for promoting hair growth.",
      description: "Herbal Haven Hair Growth Oil. A rich blend of natural oils to stimulate the scalp and encourage fast, healthy hair growth.",
      price: 1200,
      category: "hair-care",
      productLine: "organics",
      image: "/images/36-herbs-oil.png",
      images: ["/images/36-herbs-oil.png"],
      variants: [
        {
          size: "200g",
          price: 1200
        }
      ],
      benefits: ["Promotes hair growth", "Stimulates scalp"],
      howToUse: ["Massage into the scalp and leave on for a few hours before washing."]
    },
    {
      id: "o14",
      name: "Anti-Dandruff Hair Oil",
      shortDescription: "Specialized herbal oil to fight dandruff.",
      description: "Herbal Haven Anti-Dandruff Hair Oil. Treats the scalp to remove flakiness and prevent dandruff from returning.",
      price: 1300,
      category: "hair-care",
      productLine: "organics",
      image: "/images/placeholder.png",
      images: ["/images/placeholder.png"],
      variants: [
        {
          size: "200g",
          price: 1300
        }
      ],
      benefits: ["Removes dandruff", "Soothes flaky scalp"],
      howToUse: ["Apply generously to the scalp and leave on before shampooing."]
    },
    {
      id: "o15",
      name: "Anti-Dandruff Hair Shampoo",
      shortDescription: "Herbal shampoo for a dandruff-free scalp.",
      description: "Herbal Haven Anti-Dandruff Hair Shampoo. Cleanses the scalp effectively while fighting dandruff and soothing irritation.",
      price: 1250,
      category: "hair-care",
      productLine: "organics",
      image: "/images/placeholder.png",
      images: ["/images/placeholder.png"],
      variants: [
        {
          size: "200g",
          price: 1250
        }
      ],
      benefits: ["Fights dandruff", "Soothes irritation"],
      howToUse: ["Apply to wet hair, focus on the scalp, lather, and rinse."]
    },
    {
      id: "p11",
      name: "Dokht Heels",
      shortDescription: "Elegant Dokht heels.",
      description: "Beautiful Dokht heels designed for elegance and style. Perfect for special occasions or adding a touch of class to your everyday look.",
      price: 1900,
      image: "/images/dokht1.jpeg",
      images: ["/images/dokht1.jpeg"],
      category: "HEELS",
      productLine: "footwear",
      sizes: [
        {
          label: "EU 37",
          price: 1900
        },
        {
          label: "EU 39",
          price: 1900
        }
      ],
      careInstructions: ["Wipe clean with a damp cloth", "Avoid direct sunlight"]
    },
    {
      id: "p12",
      name: "Dokht Slides",
      shortDescription: "Comfortable Dokht slides.",
      description: "Comfortable and casual Dokht slides designed for everyday wear. Slip into maximum comfort with a minimalist design.",
      price: 1800,
      image: "/images/dokht2.jpeg",
      images: ["/images/dokht2.jpeg"],
      category: "FLATS",
      productLine: "footwear",
      sizes: [
        {
          label: "EU 36",
          price: 1800
        },
        {
          label: "EU 38",
          price: 1800
        },
        {
          label: "EU 39",
          price: 1800
        },
        {
          label: "EU 40",
          price: 1800
        },
        {
          label: "EU 41",
          price: 1800
        }
      ],
      careInstructions: ["Wipe clean with a damp cloth", "Store in a cool dry place"]
    }
];

export const footwearProducts = products.filter(p => p.productLine === 'footwear');
