// AUTO-GENERATED by scripts/generate-products.ts from content/testimonials/*.json
// DO NOT EDIT THIS FILE MANUALLY - edit the JSON files in content/testimonials/ instead.

export type Testimonial = {
    id: string;
    name: string;
    city?: string;
    date?: string;
    purchased?: string;
    rating?: number;
    comment: string;
};
export const testimonialsData: Testimonial[] = [
    {
      id: "t1",
      name: "Ayesha K.",
      rating: 5,
      comment: "The Rosemary Hair Toner is a game changer! My hair feels so much stronger and my hair fall has visibly reduced. Highly recommended!"
    },
    {
      id: "t2",
      name: "Sana M.",
      rating: 5,
      comment: "I've been using the Whitening Cream for two weeks now and my skin is literally glowing. It feels so natural and absorbs quickly!"
    },
    {
      id: "t3",
      name: "Fatima R.",
      rating: 4,
      comment: "The Teeth Whitening Powder works exactly as described. I noticed a difference after just a few uses. Plus, it really helped soothe my gums."
    },
    {
      id: "t4",
      name: "Hira A.",
      rating: 5,
      comment: "This Ubtan is amazing. It made my skin so tight and bright. I use it twice a week and my acne is completely gone!"
    },
    {
      id: "t5",
      name: "Zoya F.",
      rating: 5,
      comment: "In love with my new Dokht Heels! They are super elegant but still comfortable enough to wear at a long wedding event."
    },
    {
      id: "t6",
      name: "Mariam S.",
      rating: 5,
      comment: "The Dokht Slides are my go-to for everyday wear now. Minimalist, chic, and ridiculously comfortable."
    }
];
