/**
 * Prebuild Data Generation Script
 *
 * Reads all JSON files from content/products/ and content/testimonials/,
 * and generates data/products.ts and data/testimonials.ts with proper
 * TypeScript types and exports.
 *
 * This script runs automatically before `next dev` and `next build`
 * (see package.json scripts) so the generated TS files are always in sync
 * with the JSON content files managed by Decap CMS.
 *
 * Usage: npx tsx scripts/generate-products.ts
 */

import * as fs from "fs";
import * as path from "path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface SizeOption {
  label: string;
  price: number;
}

interface VariantOption {
  size: string;
  price: number;
}

interface ContentProduct {
  id: string;
  name: string;
  shortDescription: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  badge?: string;
  category: string;
  productLine: "footwear" | "organics" | "clothing";
  weight?: string;
  sizes?: SizeOption[];
  variants?: VariantOption[];
  colors?: string[];
  ingredients?: string[];
  howToUse?: string[];
  careInstructions?: string[];
  benefits?: string[];
  sizeOptions?: SizeOption[];
  skinHairType?: string;
  usage?: string;
  scale?: number;
  rotate?: number;
}

interface ContentTestimonial {
  id: string;
  name: string;
  city?: string;
  date?: string;
  purchased?: string;
  rating?: number;
  comment: string;
}
// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Reads all .json files from a directory, parses them, and returns them sorted by id.
 */
function readJsonDir<T extends { id: string }>(dirPath: string): T[] {
  const fullPath = path.resolve(process.cwd(), dirPath);

  if (!fs.existsSync(fullPath)) {
    console.warn(`Warning: Directory not found: ${dirPath}`);
    return [];
  }

  const files = fs.readdirSync(fullPath).filter((f) => f.endsWith(".json"));

  if (files.length === 0) {
    console.warn(`Warning: No JSON files found in: ${dirPath}`);
    return [];
  }

  const items: T[] = files.map((file) => {
    const filePath = path.join(fullPath, file);
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as T;
  });

  // Sort by id for deterministic output
  items.sort((a, b) => a.id.localeCompare(b.id, undefined, { numeric: true }));

  return items;
}

/**
 * Converts a JSON value to its TypeScript literal representation.
 * Handles strings, numbers, booleans, arrays, and objects.
 */
function toTsLiteral(value: unknown, indent = 2): string {
  const pad = " ".repeat(indent);

  if (value === null || value === undefined) {
    return "undefined";
  }

  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => toTsLiteral(v, indent + 2));
    // Single-line for short arrays of primitives
    if (value.every((v) => typeof v !== "object" || v === null)) {
      return `[${items.join(", ")}]`;
    }
    return `[\n${items.map((i) => `${pad}  ${i}`).join(",\n")}\n${pad}]`;
  }

  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return "{}";
    const entries = keys
      .map((k) => {
        const v = obj[k];
        if (v === undefined) return null; // Skip undefined fields
        return `${pad}  ${k}: ${toTsLiteral(v, indent + 2)}`;
      })
      .filter(Boolean);
    return `{\n${entries.join(",\n")}\n${pad}}`;
  }

  return String(value);
}

// ─── Product Generation ──────────────────────────────────────────────────────

function generateProductsData(): void {
  console.log("Generating data/products.ts from content/products/*.json ...");

  const products = readJsonDir<ContentProduct>("content/products");

  if (products.length === 0) {
    console.warn("Warning: No products found! data/products.ts will have an empty array.");
  }

  const productLiterals = products.map((p) => toTsLiteral(p, 4));

  const output = `// AUTO-GENERATED by scripts/generate-products.ts from content/products/*.json
// DO NOT EDIT THIS FILE MANUALLY - edit the JSON files in content/products/ instead.

export type Product = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    price: number;
    originalPrice?: number;
    image: string;
    images?: string[];
    badge?: string;
    category: string;
    productLine: 'footwear' | 'organics' | 'clothing';
    weight?: string;
    sizes?: { label: string; price: number }[];
    variants?: { size: string; price: number }[];
    colors?: string[];
    ingredients?: string[];
    howToUse?: string[];
    careInstructions?: string[];
    benefits?: string[];
    sizeOptions?: { label: string; price: number }[];
    skinHairType?: string;
    usage?: string;
    scale?: number;
    rotate?: number;
};

export const products: Product[] = [
${productLiterals.map((p) => `    ${p}`).join(",\n")}
];

export const footwearProducts = products.filter(p => p.productLine === 'footwear');
`;

  const outPath = path.resolve(process.cwd(), "data/products.ts");
  fs.writeFileSync(outPath, output, "utf-8");
  console.log(`Generated data/products.ts with ${products.length} products.`);
}

// ─── Testimonial Generation ──────────────────────────────────────────────────

function generateTestimonialsData(): void {
  console.log("Generating data/testimonials.ts from content/testimonials/*.json ...");

  const testimonials = readJsonDir<ContentTestimonial>("content/testimonials");

  if (testimonials.length === 0) {
    console.warn("Warning: No testimonials found! data/testimonials.ts will have an empty array.");
  }

  const testimonialLiterals = testimonials.map((t) => toTsLiteral(t, 4));

  const output = `// AUTO-GENERATED by scripts/generate-products.ts from content/testimonials/*.json
// DO NOT EDIT THIS FILE MANUALLY - edit the JSON files in content/testimonials/ instead.

export type Testimonial = {
    id: string;
    name: string;
    city?: string;
    date?: string;
    purchased?: string;
    rating?: number;
    comment: string;
};
export const testimonialsData: Testimonial[] = [
${testimonialLiterals.map((t) => `    ${t}`).join(",\n")}
];
`;

  const outPath = path.resolve(process.cwd(), "data/testimonials.ts");
  fs.writeFileSync(outPath, output, "utf-8");
  console.log(`Generated data/testimonials.ts with ${testimonials.length} testimonials.`);
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main(): void {
  console.log("=== MJR Data Generation ===");
  generateProductsData();
  generateTestimonialsData();
  console.log("=== Done ===");
}

main();